In [116]:
import random
import string
import numpy as np



In [117]:
# Calcule a aptidão máxima com base na população, aptidão máxima de 28
def calculate_max_fitness():
    i = board_size - 1
    max_fitness = 0
    while i > 0:
        max_fitness += i
        i -= 1
    return max_fitness

# Gera um indivíduo aleatório com base no tamanho do tabuleiro
def random_individual(board_size):
    return [ random.randint(0,board_size-1) for _ in range(board_size) ]

# Define a aptidão de um indivíduo com base no número de rainhas que não atacam checando a diagonal esquerda e direita e a horizontal.
def fitness(individual):
    horizontal_collisions = sum([individual.count(queen)-1 for queen in individual])/2
    diagonal_collisions = 0

    n = len(individual)
    left_diagonal = [0] * 2*n
    right_diagonal = [0] * 2*n
    for i in range(n):
        left_diagonal[i + individual[i] - 1] += 1
        right_diagonal[len(individual) - i + individual[i] - 2] += 1

    for i in range(2*n-1):
        counter = 0
        if left_diagonal[i] > 1:
            counter += left_diagonal[i]-1
        if right_diagonal[i] > 1:
            counter += right_diagonal[i]-1
        diagonal_collisions += counter / (n-abs(i-n+1))
    return int(max_fitness - (horizontal_collisions + diagonal_collisions))

# Calcule a probabilidade de um indivíduo com base em sua aptidão em comparação com max_fitness que é maximizado e o máx é 28.
def probability(individual, fitness):
    return fitness(individual) / max_fitness

# Pegue um indivíduo aleatório com base na população por probabilidade
def random_pick(population, probabilities):
    populationpro = zip(population, probabilities)
    total = sum(w for c, w in populationpro)
    r = random.uniform(0, total)
    upto = 0
    for c, w in zip(population, probabilities):
        if upto + w >= r:
            return c
        upto += w
    assert False 

# Retorne um novo indivíduo, seus genes são de 2 pais x e y com um aleatório 
def crossover(x, y):
    n = len(x)
    #c = 4
    c = random.randint(0, n - 1)
    return x[0:c] + y[c:n]

# Retorna um indivíduo com um gene aleatório modificado entre 1 e n do tamanho do tabuleiro
def mutate(x):
    n = len(x)
    c = random.randint(0, n - 1)
    m = random.randint(1, n)
    x[c] = m
    return x

#Criação de novas populações com indivíduos aleatórios 
def genetic_queen(population, fitness):
    #Probabilidade de mutação
    new_population = []
    probabilities = [probability(n, fitness) for n in population]
    for i in range(len(population)):
        x = random_pick(population, probabilities)
        y = random_pick(population, probabilities)
        child = crossover(x, y)
        if random.random() < mutation_probability:
            child = mutate(child)
        new_population.append(child)
        if fitness(child) == max_fitness: break
    return new_population


In [118]:
# Main
if __name__ == "__main__":
    board_size = 8 # setando o número de rainhas dispostas no tabuleiro
    max_pop = 100 # tamanho da população
    mutation_probability = 0.8 #Probabilidade de mutação 80%
    max_fitness = calculate_max_fitness() #Calcula a aptidão máxima  de cada geração
    population = [random_individual(board_size) for _ in range(max_pop)] #criação da nova população de acordo com as rainhas e a população inicial de 100
    generation = 1
    while not max_fitness in [fitness(x) for x in population]: 
        population = genetic_queen(population, fitness)
        print("Generation = " + str(generation) + " | Maximum fitness = {}".format(max([fitness(n) for n in population])))
        generation += 1
    print("Solução na geração {}!".format(generation-1))
    for x in population:
        if fitness(x) == max_fitness:
            #print_individual(x)
            #print_table(x)
            print(x)
            solution = x
            

Generation = 1 | Maximum fitness = 26
Generation = 2 | Maximum fitness = 27
Generation = 3 | Maximum fitness = 27
Generation = 4 | Maximum fitness = 26
Generation = 5 | Maximum fitness = 26
Generation = 6 | Maximum fitness = 27
Generation = 7 | Maximum fitness = 27
Generation = 8 | Maximum fitness = 27
Generation = 9 | Maximum fitness = 27
Generation = 10 | Maximum fitness = 26
Generation = 11 | Maximum fitness = 26
Generation = 12 | Maximum fitness = 27
Generation = 13 | Maximum fitness = 27
Generation = 14 | Maximum fitness = 27
Generation = 15 | Maximum fitness = 27
Generation = 16 | Maximum fitness = 27
Generation = 17 | Maximum fitness = 27
Generation = 18 | Maximum fitness = 26
Generation = 19 | Maximum fitness = 27
Generation = 20 | Maximum fitness = 26
Generation = 21 | Maximum fitness = 26
Generation = 22 | Maximum fitness = 27
Generation = 23 | Maximum fitness = 26
Generation = 24 | Maximum fitness = 26
Generation = 25 | Maximum fitness = 26
Generation = 26 | Maximum fitness 

Generation = 213 | Maximum fitness = 26
Generation = 214 | Maximum fitness = 27
Generation = 215 | Maximum fitness = 26
Generation = 216 | Maximum fitness = 27
Generation = 217 | Maximum fitness = 26
Generation = 218 | Maximum fitness = 27
Generation = 219 | Maximum fitness = 26
Generation = 220 | Maximum fitness = 26
Generation = 221 | Maximum fitness = 26
Generation = 222 | Maximum fitness = 27
Generation = 223 | Maximum fitness = 26
Generation = 224 | Maximum fitness = 26
Generation = 225 | Maximum fitness = 27
Generation = 226 | Maximum fitness = 27
Generation = 227 | Maximum fitness = 26
Generation = 228 | Maximum fitness = 26
Generation = 229 | Maximum fitness = 26
Generation = 230 | Maximum fitness = 26
Generation = 231 | Maximum fitness = 27
Generation = 232 | Maximum fitness = 27
Generation = 233 | Maximum fitness = 27
Generation = 234 | Maximum fitness = 26
Generation = 235 | Maximum fitness = 26
Generation = 236 | Maximum fitness = 27
Generation = 237 | Maximum fitness = 26


Generation = 421 | Maximum fitness = 26
Generation = 422 | Maximum fitness = 26
Generation = 423 | Maximum fitness = 26
Generation = 424 | Maximum fitness = 26
Generation = 425 | Maximum fitness = 26
Generation = 426 | Maximum fitness = 26
Generation = 427 | Maximum fitness = 26
Generation = 428 | Maximum fitness = 26
Generation = 429 | Maximum fitness = 27
Generation = 430 | Maximum fitness = 26
Generation = 431 | Maximum fitness = 26
Generation = 432 | Maximum fitness = 26
Generation = 433 | Maximum fitness = 26
Generation = 434 | Maximum fitness = 26
Generation = 435 | Maximum fitness = 26
Generation = 436 | Maximum fitness = 26
Generation = 437 | Maximum fitness = 26
Generation = 438 | Maximum fitness = 26
Generation = 439 | Maximum fitness = 26
Generation = 440 | Maximum fitness = 26
Generation = 441 | Maximum fitness = 26
Generation = 442 | Maximum fitness = 27
Generation = 443 | Maximum fitness = 27
Generation = 444 | Maximum fitness = 26
Generation = 445 | Maximum fitness = 26


Generation = 633 | Maximum fitness = 26
Generation = 634 | Maximum fitness = 26
Generation = 635 | Maximum fitness = 27
Generation = 636 | Maximum fitness = 26
Generation = 637 | Maximum fitness = 26
Generation = 638 | Maximum fitness = 26
Generation = 639 | Maximum fitness = 26
Generation = 640 | Maximum fitness = 27
Generation = 641 | Maximum fitness = 27
Generation = 642 | Maximum fitness = 26
Generation = 643 | Maximum fitness = 26
Generation = 644 | Maximum fitness = 26
Generation = 645 | Maximum fitness = 26
Generation = 646 | Maximum fitness = 26
Generation = 647 | Maximum fitness = 26
Generation = 648 | Maximum fitness = 27
Generation = 649 | Maximum fitness = 27
Generation = 650 | Maximum fitness = 26
Generation = 651 | Maximum fitness = 27
Generation = 652 | Maximum fitness = 26
Generation = 653 | Maximum fitness = 26
Generation = 654 | Maximum fitness = 27
Generation = 655 | Maximum fitness = 26
Generation = 656 | Maximum fitness = 27
Generation = 657 | Maximum fitness = 26


Generation = 843 | Maximum fitness = 26
Generation = 844 | Maximum fitness = 26
Generation = 845 | Maximum fitness = 26
Generation = 846 | Maximum fitness = 27
Generation = 847 | Maximum fitness = 26
Generation = 848 | Maximum fitness = 27
Generation = 849 | Maximum fitness = 26
Generation = 850 | Maximum fitness = 27
Generation = 851 | Maximum fitness = 26
Generation = 852 | Maximum fitness = 27
Generation = 853 | Maximum fitness = 27
Generation = 854 | Maximum fitness = 26
Generation = 855 | Maximum fitness = 26
Generation = 856 | Maximum fitness = 26
Generation = 857 | Maximum fitness = 26
Generation = 858 | Maximum fitness = 26
Generation = 859 | Maximum fitness = 26
Generation = 860 | Maximum fitness = 26
Generation = 861 | Maximum fitness = 27
Generation = 862 | Maximum fitness = 26
Generation = 863 | Maximum fitness = 26
Generation = 864 | Maximum fitness = 27
Generation = 865 | Maximum fitness = 26
Generation = 866 | Maximum fitness = 26
Generation = 867 | Maximum fitness = 26


In [119]:
#Alteração do índice para printar o tabuleiro de 0 a 7 da solução encontrada
print(solution)
list = []
for l in range(8):
       list.append(solution[l]-1)
    
print(list)

[4, 8, 1, 3, 6, 2, 7, 5]
[3, 7, 0, 2, 5, 1, 6, 4]


In [120]:
def print_table(list):
    lista = []
    tabu = np.zeros((8,8), dtype=int)
    for l in range(8):
        tabu[l][list[l]] = 1
        #print (tabu)
    lista.append(tabu)    
    return lista
 


In [121]:
lista = print_table(list)

#Printando a matriz da solução
for i, elemLi in enumerate(lista):
    print()
    print('Matriz de solução', i, ':')
    print(elemLi)


Matriz de solução 0 :
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]]
